// src/shared/utils/pdfGenerator.ts
// Generates HTML for PDF export of receipts

import { Invoice } from "../types/invoice";

/**
 * Generates an HTML string for receipt PDF export
 * @param invoice - The invoice data to generate PDF from
 * @returns HTML string formatted for PDF generation
 */
export function generateReceiptHTML(invoice: Invoice): string {
  const { title, date, items, totals, totalAmount } = invoice;
  
  // Format date for display
  const formattedDate = new Date(date).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  // Generate items rows
  const itemsHTML = items
    .map(
      (item) => `
        <tr>
          <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">
            <div style="font-weight: 500; color: #111827; margin-bottom: 4px;">
              ${escapeHtml(item.name)}
            </div>
            ${
              item.splitBetween.length > 0
                ? `<div style="font-size: 12px; color: #6b7280;">
                    Split: ${item.splitBetween.map(escapeHtml).join(", ")}
                   </div>`
                : ""
            }
          </td>
          <td style="padding: 12px; text-align: right; font-weight: 600; color: #111827; border-bottom: 1px solid #e5e7eb;">
            $${item.price.toFixed(2)}
          </td>
        </tr>
      `
    )
    .join("");

  // Generate totals rows
  const totalsHTML = totals
    .map(
      (person) => `
        <tr>
          <td style="padding: 10px 12px; color: #374151; font-weight: 500;">
            ${escapeHtml(person.name)}
          </td>
          <td style="padding: 10px 12px; text-align: right; font-weight: 600; color: #111827;">
            $${person.total.toFixed(2)}
          </td>
        </tr>
      `
    )
    .join("");

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title || "Receipt")}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      color: #111827;
      padding: 40px 20px;
      background: #ffffff;
    }
    .container {
      max-width: 700px;
      margin: 0 auto;
    }
    .header {
      margin-bottom: 32px;
      padding-bottom: 24px;
      border-bottom: 2px solid #d97757;
    }
    .title {
      font-size: 28px;
      font-weight: 700;
      color: #111827;
      margin-bottom: 8px;
    }
    .date {
      font-size: 14px;
      color: #6b7280;
    }
    .section {
      margin-bottom: 32px;
    }
    .section-title {
      font-size: 18px;
      font-weight: 600;
      color: #111827;
      margin-bottom: 16px;
      padding-bottom: 8px;
      border-bottom: 1px solid #e5e7eb;
    }
    table {
      width: 100%;
      border-collapse: collapse;
    }
    .total-row {
      background-color: #fef3e6;
      font-weight: 700;
    }
    .total-row td {
      padding: 16px 12px !important;
      font-size: 18px;
      border-top: 2px solid #d97757;
      border-bottom: 2px solid #d97757;
    }
    .footer {
      margin-top: 48px;
      padding-top: 24px;
      border-top: 1px solid #e5e7eb;
      text-align: center;
      color: #9ca3af;
      font-size: 12px;
    }
    @media print {
      body {
        padding: 20px;
      }
      .footer {
        position: fixed;
        bottom: 20px;
        left: 0;
        right: 0;
      }
    }
  </style>
</head>
<body>
  <div class="container">
    <!-- Header -->
    <div class="header">
      <div class="title">${escapeHtml(title || "Receipt")}</div>
      <div class="date">${formattedDate}</div>
    </div>

    <!-- Items Section -->
    <div class="section">
      <div class="section-title">Items</div>
      <table>
        <tbody>
          ${itemsHTML}
          <tr class="total-row">
            <td>Total Amount</td>
            <td style="text-align: right;">$${totalAmount.toFixed(2)}</td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Split Summary Section -->
    ${
      totals.length > 0
        ? `
    <div class="section">
      <div class="section-title">Split Summary</div>
      <table>
        <tbody>
          ${totalsHTML}
        </tbody>
      </table>
    </div>
    `
        : ""
    }

    <!-- Footer -->
    <div class="footer">
      Generated by SplitMate • ${new Date().toLocaleDateString("en-US")}
    </div>
  </div>
</body>
</html>
  `.trim();
}

/**
 * Escapes HTML special characters to prevent XSS
 * @param text - Text to escape
 * @returns Escaped text safe for HTML insertion
 */
function escapeHtml(text: string): string {
  const map: Record<string, string> = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#039;",
  };
  return text.replace(/[&<>"']/g, (char) => map[char]);
}
